name: Manter Supabase Ativo

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar requisição para o Supabase
        run: |
          curl -i -X POST "${{ secrets.VITE_SUPABASE_URL }}/rest/v1/rpc/keep_alive_safe_ping" \
          -H "apikey: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}" \
          -H "Content-Type: application/json"