name: Manter Supabase Ativo

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
      - name: Inserir registro de atividade no Supabase
        run: |
          curl -i -X POST "${{ secrets.VITE_SUPABASE_URL }}/rest/v1/github_pings" \
          -H "apikey: ${{ secrets.SERVICE }}" \
          -H "Authorization: Bearer ${{ secrets.SERVICE }}" \
          -H "Content-Type: application/json" \
          -H "Prefer: return=minimal" \
          --data '{}'
